
ccflags-y += -I$(srctree)/drivers/net/ethernet/aquantia/atlantic-fwd/
ccflags-y += -I$(srctree)/techpack/data-eth/drivers/ioss/include/

obj-$(CONFIG_AQFWD_IOSS) += aqc-ioss.o
aqc-ioss-objs := aqc_ioss.o
